-- This SQL is generated by `prisma migrate diff --from-config-datasource --to-schema prisma/schema.prisma --script`
-- after `prisma migrate dev` could not run interactively in the Codex terminal.

-- AlterTable
ALTER TABLE "outbox_events" DROP CONSTRAINT "outbox_events_pkey",
ADD COLUMN     "dedupe_key" TEXT NOT NULL,
DROP COLUMN "id",
ADD COLUMN     "id" UUID NOT NULL,
ADD CONSTRAINT "outbox_events_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "sync_object_index" DROP CONSTRAINT "sync_object_index_pkey",
DROP COLUMN "id",
ADD COLUMN     "id" UUID NOT NULL,
ADD CONSTRAINT "sync_object_index_pkey" PRIMARY KEY ("id");

-- CreateIndex
CREATE UNIQUE INDEX "outbox_events_dedupe_key_key" ON "outbox_events"("dedupe_key");
